# Generated by Django 3.1 on 2020-08-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0002_auto_20200825_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bravo_library.client'),
        ),
    ]
