# Generated by Django 3.1 on 2020-08-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0003_bookinstance_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='client_id',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='client',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bravo_library.client'),
        ),
    ]
