# Generated by Django 3.1 on 2020-08-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0005_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='imprint',
        ),
    ]
