# Generated by Django 3.1 on 2020-08-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0009_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('L', 'lent'), ('a', 'Available'), ('r', 'Reserved')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('L', 'lent'), ('a', 'Available'), ('r', 'Reserved')], default='a', max_length=1),
        ),
    ]
