# Generated by Django 3.1 on 2020-08-25 16:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0010_auto_20200825_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('summary', models.TextField(max_length=500, verbose_name='Book summary')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bravo_library.author')),
                ('genre', models.ManyToManyField(to='bravo_library.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterBookMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('M', 'Maintenance'), ('L', 'lent'), ('A', 'Available'), ('R', 'Reserved')], default='A', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bravo_library.registerbook')),
                ('client', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bravo_library.client')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='client',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
