# Generated by Django 3.1 on 2020-08-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0013_auto_20200825_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='registerbook',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='registerbookmovement',
            name='book',
        ),
        migrations.RemoveField(
            model_name='registerbookmovement',
            name='client',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_movement',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=0, max_length=100, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_movement',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default=0, max_length=50, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=0, max_length=13, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Disponível'), ('E', 'Emprestado'), ('R', 'Reservado')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default=0, max_length=500, verbose_name='Book summary'),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=0, max_length=200, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='RegisterBook',
        ),
        migrations.DeleteModel(
            name='RegisterBookMovement',
        ),
    ]
