# Generated by Django 3.1 on 2020-08-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0014_auto_20200825_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bravo_library.client'),
        ),
    ]
