# Generated by Django 3.1 on 2020-08-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0015_book_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='client_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bravo_library.client'),
        ),
    ]
