# Generated by Django 3.1 on 2020-08-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0018_auto_20200825_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('Disponivel', 'Disponível'), ('Emprestado', 'Emprestado'), ('Reservado', 'Reservado')], default='D', max_length=30),
        ),
    ]
