# Generated by Django 3.1 on 2020-08-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0019_auto_20200825_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reserve',
            field=models.BooleanField(default=False, verbose_name='is reserved'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado')], default='disponivel', max_length=30),
        ),
    ]
