# Generated by Django 3.1 on 2020-08-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0020_auto_20200825_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='delivery_date',
            field=models.DateTimeField(null=True, verbose_name='Delivery Date'),
        ),
    ]
