# Generated by Django 3.1 on 2020-08-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravo_library', '0022_auto_20200826_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_movement',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='delivery_date',
            field=models.DateField(null=True, verbose_name='Delivery Date'),
        ),
    ]
